# Generated by Django 4.1.1 on 2022-09-29 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_holidays'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hollydays',
        ),
    ]
