# Generated by Django 4.1.1 on 2022-09-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_delete_hollydays'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidays',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
