# Generated by Django 4.1.1 on 2022-09-29 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_holidays_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidays',
            name='begin',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='holidays',
            name='end',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
