# Generated by Django 4.1.1 on 2022-10-01 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_fullservice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fullservice',
            old_name='lunch_type',
            new_name='meal_type',
        ),
    ]
