# Generated by Django 4.1.2 on 2022-10-13 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_rename_lunch_type_fullservice_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='mail',
            field=models.EmailField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100)]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MaxLengthValidator(20)]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone_number',
            field=models.CharField(default='', max_length=10, validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(10)]),
        ),
    ]
