# Generated by Django 4.1 on 2022-10-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_reservation_mail_alter_reservation_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='warning',
            field=models.BooleanField(default=False),
        ),
    ]
