# Generated by Django 4.1 on 2022-10-26 21:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_client_warning'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='first_name',
            field=models.CharField(default='', max_length=20, validators=[django.core.validators.MaxLengthValidator(20)]),
        ),
    ]
