# Generated by Django 4.1 on 2022-10-26 21:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_reservation_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='first_name',
            field=models.CharField(default='', max_length=20, validators=[django.core.validators.MaxLengthValidator(20)]),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
