# Generated by Django 4.1 on 2022-11-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_reservation_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('receptor', models.CharField(default='', max_length=100)),
                ('hour', models.CharField(default='', max_length=6)),
                ('date', models.DateField(default='')),
                ('nb_people', models.IntegerField(default=0)),
            ],
        ),
    ]
