# Generated by Django 4.1 on 2022-11-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_mailerror_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailerror',
            name='treated',
            field=models.BooleanField(default=False),
        ),
    ]
