# Generated by Django 4.1 on 2022-11-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_mailerror_treated'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='meal_type',
            field=models.CharField(choices=[('M', 'Midi'), ('D', 'Diner')], default='M', max_length=1),
        ),
    ]
